#!/usr/bin/env python3
"""Verify the saturated-spoke strengthening of the rural two-pair barrier."""

from __future__ import annotations

from contextlib import redirect_stdout
from importlib.util import module_from_spec, spec_from_file_location
from io import StringIO
from itertools import combinations
from pathlib import Path
import sys


LOCAL_DEPS = Path(__file__).resolve().parents[1] / "active" / "runtime" / "deps"
if LOCAL_DEPS.is_dir():
    sys.path.insert(0, str(LOCAL_DEPS))

import networkx as nx


SOURCE = Path(__file__).with_name(
    "hc7_two_pair_rural_almost_universal_apex_barrier_verify.py"
)
spec = spec_from_file_location("rural_base", SOURCE)
if spec is None or spec.loader is None:
    raise RuntimeError(f"cannot load {SOURCE}")
base = module_from_spec(spec)
with redirect_stdout(StringIO()):
    spec.loader.exec_module(base)


graph = base.host.copy()
graph.remove_edge(base.p, (1, 1))
graph.remove_edge(base.q, (1, 3))


# Each dictionary is a colouring of G-xs, normalized so that x and s have
# colour zero.  It is deliberately stored as a literal certificate rather
# than regenerated by a colouring solver.
RESPONSES = {
    (0, 1): {
        (0, 0): 0, (0, 1): 0, "p": 1, "q": 2, "Top": 3,
        (0, 2): 4, (0, 3): 0, (1, 2): 3, (0, 4): 4,
        (1, 1): 1, (1, 3): 2, (1, 4): 3, (1, 0): 5,
        (2, 4): 0, (2, 0): 3, "Bottom": 4, (2, 3): 5,
        (2, 2): 0, (2, 1): 5,
    },
    (0, 4): {
        (0, 0): 0, (0, 4): 0, "p": 1, "q": 2, "Top": 3,
        (0, 1): 4, (0, 2): 0, (0, 3): 4, (1, 2): 3,
        (1, 1): 1, (1, 0): 3, (1, 3): 2, (1, 4): 5,
        (2, 4): 0, (2, 0): 4, "Bottom": 3, (2, 3): 4,
        (2, 1): 0, (2, 2): 5,
    },
    (1, 0): {
        (0, 0): 0, (1, 0): 0, "p": 1, "q": 2, "Top": 3,
        (0, 1): 4, (0, 2): 0, (0, 3): 4, (0, 4): 5,
        (1, 2): 3, (1, 1): 1, (1, 3): 0, (2, 2): 4,
        (2, 1): 0, "Bottom": 3, (2, 3): 5, (2, 4): 4,
        (2, 0): 5, (1, 4): 3,
    },
    (1, 4): {
        (0, 0): 0, (1, 4): 0, "p": 1, "q": 2, "Top": 3,
        (0, 1): 4, (0, 2): 0, (0, 3): 4, (0, 4): 5,
        (1, 2): 3, (1, 3): 2, (1, 1): 1, (1, 0): 3,
        (2, 4): 4, (2, 0): 0, "Bottom": 3, (2, 3): 5,
        (2, 1): 4, (2, 2): 0,
    },
    "Top": {
        (0, 0): 0, "Top": 0, "p": 1, "q": 2, (0, 1): 3,
        (0, 2): 4, (0, 3): 3, (1, 2): 0, (0, 4): 5,
        (1, 1): 1, (1, 0): 4, (1, 3): 2, (1, 4): 3,
        (2, 4): 0, (2, 0): 3, "Bottom": 4, (2, 1): 5,
        (2, 2): 3, (2, 3): 5,
    },
    "p": {
        (0, 0): 0, "p": 0, "q": 1, (1, 2): 2, (0, 2): 3,
        (0, 3): 4, "Top": 2, (0, 1): 4, (0, 4): 3,
        (1, 1): 0, (1, 3): 1, (1, 0): 2, (1, 4): 5,
        (2, 4): 3, (2, 0): 4, "Bottom": 2, (2, 3): 4,
        (2, 1): 3, (2, 2): 5,
    },
    "q": {
        (0, 0): 0, "q": 0, "p": 1, (1, 2): 2, (0, 2): 3,
        (0, 3): 4, "Top": 2, (0, 1): 4, (0, 4): 3,
        (1, 1): 1, (1, 3): 0, (1, 0): 2, (1, 4): 5,
        (2, 4): 3, (2, 0): 4, "Bottom": 2, (2, 3): 4,
        (2, 1): 3, (2, 2): 5,
    },
}


def has_edge_between(left: set[object], right: set[object]) -> bool:
    return any(graph.has_edge(x, y) for x in left for y in right)


def verify_response(spoke: object, colouring: dict[object, int]) -> None:
    assert set(colouring) == set(graph)
    assert colouring[base.x] == colouring[spoke] == 0
    for x, y in graph.edges():
        if {x, y} == {base.x, spoke}:
            continue
        assert colouring[x] != colouring[y]

    palette = {1, 2, 3, 4, 5}
    assert {
        colouring[y] for y in graph.neighbors(base.x) if y != spoke
    } == palette
    assert {
        colouring[y] for y in graph.neighbors(spoke) if y != base.x
    } == palette


def main() -> None:
    assert nx.node_connectivity(graph) == 7
    assert set(graph.edges()) < set(base.host.edges())
    assert nx.check_planarity(graph.subgraph(base.core))[0]
    print("host: 7-connected and K7-minor-free by the two-apex argument")

    assert set(graph.neighbors(base.x)) == set(base.boundary)
    assert not has_edge_between(base.left, base.right)
    assert nx.is_connected(graph.subgraph(base.right))
    rooted = graph.subgraph(base.left | base.I | base.J).copy()
    assert nx.check_planarity(rooted)[0]
    assert not base.linked(rooted, (base.p, base.u), (base.q, base.v))
    print("disk: exact seven-boundary and alternating two-pair obstruction")

    for row in base.rows.values():
        assert nx.is_connected(graph.subgraph(row))
        assert has_edge_between({base.a}, row)
    for first, second in combinations(base.rows.values(), 2):
        assert has_edge_between(first, second)
    print("rows: all five named traces and adjacencies remain valid")

    for deleted in combinations(base.B, 2):
        clique = base.explicit_k5[frozenset(deleted)]
        assert all(graph.has_edge(x, y) for x, y in combinations(clique, 2))
    print("transversal: no pair among the three omitted labels hits every K5")

    assert set(RESPONSES) == set(graph.neighbors(base.x))
    for spoke, colouring in RESPONSES.items():
        verify_response(spoke, colouring)
    print("responses: every spoke has a fully endpoint-saturated 6-colouring")

    assert all(base.colouring[x] != base.colouring[y] for x, y in graph.edges())
    print("criticality gap: the host itself still has a proper 6-colouring")


if __name__ == "__main__":
    main()
