#!/usr/bin/env python3
"""Falsify the full seven-terminal kernel mechanism in the order-six cell.

Exploratory only.  For every tested noncommon boundary state and every
candidate reserved pair, require simultaneous closure against

* every labelled edge-minimal three-connected graph on seven terminals;
* every labelled terminal-irreducible order-eight rooted kernel, allowing
  deletion of the extra bag or merger into any adjacent terminal bag.

The ten rooted order-eight types were independently generated by ``geng``
in ``hc7_seven_terminal_kernel_dichotomy_probe.py``.
"""

from __future__ import annotations

import argparse
import itertools
import sys

sys.path.insert(0, "active/runtime/deps")
import networkx as nx  # noqa: E402

import hc7_cross_arm_overlap_three_kernel_decoder as relation
import hc7_overlap_two_kernel_probe as overlap


ROOTED_ORDER8 = (
    ("GCp`f{", 7),
    ("GCpbdw", 7),
    ("GCpbfw", 7),
    ("GCpbf{", 7),
    ("GCpbvg", 7),
    ("GCpbvk", 7),
    ("GCpbvw", 7),
    ("GCpbv{", 7),
    ("GCpdjo", 6),
    ("GCpdjs", 6),
)


def local_mask(edges):
    pairs = tuple(itertools.combinations(range(7), 2))
    index = {edge: i for i, edge in enumerate(pairs)}
    mask = 0
    for left, right in edges:
        mask |= 1 << index[relation.pair(left, right)]
    return mask


def exact_order8_option_groups():
    """Return every labelled kernel as its legal quotient-option set."""

    groups = set()
    for graph6, extra in ROOTED_ORDER8:
        graph = nx.from_graph6_bytes(graph6.encode())
        terminals = tuple(vertex for vertex in graph if vertex != extra)
        assert len(terminals) == 7
        extra_neighbours = tuple(graph[extra])
        for images in itertools.permutations(range(7)):
            image = dict(zip(terminals, images))
            base_edges = {
                relation.pair(image[left], image[right])
                for left, right in graph.edges
                if left != extra and right != extra
            }
            options = {local_mask(base_edges)}
            for owner in extra_neighbours:
                owner_image = image[owner]
                quotient_edges = set(base_edges)
                quotient_edges.update(
                    relation.pair(owner_image, image[other])
                    for other in extra_neighbours
                    if other != owner
                )
                options.add(local_mask(quotient_edges))
            groups.add(tuple(sorted(options)))
    return tuple(sorted(groups))


def lift(mask, labels, pair_index):
    pairs = tuple(itertools.combinations(range(7), 2))
    answer = 0
    for index, (left, right) in enumerate(pairs):
        if mask >> index & 1:
            answer |= 1 << pair_index[
                relation.pair(labels[left], labels[right])
            ]
    return answer


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip", type=int, default=0)
    parser.add_argument("--limit", type=int, default=1)
    args = parser.parse_args()

    cell, pairs, pair_index, states = overlap.joined_states(6)
    n, a, common, _x, p, q, terminals, *_ = cell
    noncommon = sorted(
        state
        for state in states
        if relation.common_rooted_k4(state[0], n, a, common, p, q) is None
    )
    order7 = overlap.minimal_seven_terminal_carriers()
    order8 = exact_order8_option_groups()
    detector = overlap.FastK7(n, pairs, pair_index)

    print("noncommon", len(noncommon), flush=True)
    print("order7_carriers", len(order7), flush=True)
    print("order8_option_groups", len(order8), flush=True)

    tested = 0
    for state_index in range(args.skip, min(len(noncommon), args.skip + args.limit)):
        ones, zeros = noncommon[state_index]
        valid = []
        diagnostics = {}
        for reserved in itertools.combinations(terminals, 2):
            labels = tuple(vertex for vertex in terminals if vertex not in reserved)
            bad7 = next(
                (
                    carrier
                    for carrier in order7
                    if not detector(ones | lift(carrier, labels, pair_index))
                ),
                None,
            )
            if bad7 is not None:
                diagnostics[reserved] = ("order7", bad7)
                continue
            bad8 = next(
                (
                    group
                    for group in order8
                    if not any(
                        detector(ones | lift(option, labels, pair_index))
                        for option in group
                    )
                ),
                None,
            )
            if bad8 is not None:
                diagnostics[reserved] = ("order8", bad8)
                continue
            valid.append(reserved)
        tested += 1
        print(
            "STATE",
            state_index,
            "valid",
            valid,
            "failure_kinds",
            {kind: sum(1 for value in diagnostics.values() if value[0] == kind)
             for kind in ("order7", "order8")},
            flush=True,
        )
        if not valid:
            print("COUNTERSTATE", state_index, ones, zeros, diagnostics, flush=True)
            break
    print("tested", tested, flush=True)


if __name__ == "__main__":
    main()
